server:
  port: 8081
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: 1
      logic-not-delete-value: 0

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: RSCly0412
      driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: localhost
      port: 6379
      database: 0

    cache:
      redis:
        time-to-live: 1800000 # 设置缓存过期时间
        cache-null-values: true
reggie:
  path: /Users/qiuyun/IdeaProjects/reggie_take_out/src/main/resources/static/download/